import { RED_SUITS } from './utils.js';
export class UI {
  constructor(documentRef = document) { this.document = documentRef; }
  byId(id) { return this.document.getElementById(id); }
  showScreen(id) { this.document.querySelectorAll('.sc').forEach((screen) => screen.classList.remove('on', 'screen-entering')); const screen = this.byId(id); screen.classList.add('on', 'screen-entering'); }
  flashSave() { const indicator = this.byId('saveIndicator'); if (!indicator) return; indicator.classList.remove('save-flash'); void indicator.offsetWidth; indicator.classList.add('save-flash'); }
  setMessage(text = '', className = '') { const el = this.byId('rMsg'); el.textContent = text; el.className = `rm ${className}`; }
  renderCards(id, hand, hideSecond = false) { const row = this.byId(id); row.replaceChildren(); hand.forEach((card, index) => { const div = this.document.createElement('div'); if (hideSecond && index === 1) { div.className = 'card hid card-flip'; } else { div.className = `card card-enter${RED_SUITS.has(card.s) ? ' r' : ''}`; const suit = this.document.createElement('div'); suit.className = 'ss'; suit.textContent = card.s; const value = this.document.createElement('div'); value.className = 'sv'; value.textContent = card.v; div.append(suit, value); } row.appendChild(div); }); }
  updateScore(id, value) { const el = this.byId(id); el.textContent = value; el.className = 'sc-num'; if (value > 21) el.classList.add('sc-bust'); if (value === 21) el.classList.add('sc-bj'); }
  updateBars(state) { this.byId('hudPFill').style.width = `${Math.round(state.psy)}%`; this.byId('spFill').style.width = `${Math.round(state.spec)}%`; this.byId('spVal').textContent = `${Math.round(state.spec)}%`; }
  setControls(hit, stand, deal, item = false) { this.byId('bH').disabled = !hit; this.byId('bS').disabled = !stand; this.byId('bD').style.display = deal ? 'inline-block' : 'none'; this.byId('bH').style.display = !deal ? 'inline-block' : 'none'; this.byId('bS').style.display = !deal ? 'inline-block' : 'none'; this.byId('bItem').style.display = item ? 'inline-block' : 'none'; }
  renderBattle(enemy, snap, state, hideEnemy = true) { this.byId('hudPort').textContent = enemy.icon; this.byId('hudPort').style.color = enemy.col; this.byId('hudName').textContent = enemy.name; this.byId('hudName').style.color = enemy.col; this.byId('hudSub').textContent = enemy.sub; this.byId('tblELbl').textContent = enemy.name; this.byId('hudHand').textContent = `${snap.currentHand}/${snap.totalHands}`; this.byId('spLbl').textContent = enemy.spec || enemy.barLbl; this.byId('spFill').style.background = enemy.barCol; this.renderCards('pCards', snap.playerHand, false); this.renderCards('eCards', snap.enemyHand, hideEnemy); this.updateScore('pScore', snap.playerScore); this.updateBars(state); }
  renderDialog(enemy, dialog, onChoice) { this.byId('dlgArea').style.display = 'block'; this.byId('dlgSp').textContent = enemy.name; this.byId('dlgTx').textContent = dialog.note ? `${dialog.text}\n${dialog.note}` : (dialog.tx || dialog.text); this.byId('chArea').style.display = 'block'; const grid = this.byId('chGrid'); grid.replaceChildren(); (dialog.ch || dialog.choices).forEach((choice) => { const button = this.document.createElement('button'); button.className = `ch-btn ${choice.tp || choice.type}`; button.textContent = choice.t || choice.label; button.addEventListener('click', () => onChoice(choice.tp || choice.type)); grid.appendChild(button); }); }
  hideDialog() { this.byId('dlgArea').style.display = 'none'; this.byId('chArea').style.display = 'none'; }
  renderShop(items, state, vendorText, onBuy) { this.byId('shVendorTxt').textContent = vendorText; this.byId('shGold').textContent = state.gold; const grid = this.byId('shGrid'); grid.replaceChildren(); items.forEach((item) => { const owned = state.inventory.includes(item.id); const card = this.document.createElement('button'); card.className = `sh-item${owned ? ' owned' : ''}`; card.disabled = owned; card.textContent = `${item.rare} — ${item.name}: ${item.desc} (${owned ? 'Adquirido' : `${item.price} fichas`})`; card.addEventListener('click', () => onBuy(item)); grid.appendChild(card); }); }
  renderEvent(event, onChoice) { this.byId('dlgArea').style.display = 'block'; this.byId('dlgSp').textContent = 'O Cassino'; this.byId('dlgTx').textContent = event.text; this.byId('chArea').style.display = 'block'; const grid = this.byId('chGrid'); grid.replaceChildren(); event.choices.forEach((choice) => { const button = this.document.createElement('button'); button.className = 'ch-btn'; button.textContent = choice.label; button.addEventListener('click', () => onChoice(choice.effect)); grid.appendChild(button); }); this.showScreen('sG'); }
  renderMap(enemies, dealer, state, current) { const track = this.byId('mTrack'); track.replaceChildren(); [...enemies, dealer].forEach((enemy, index) => { const node = this.document.createElement('div'); const done = index < state.curEnemy; const cur = enemy.id === current.id; node.className = `m-nd ${done ? 'done' : cur ? 'cur' : 'lock'}`; node.textContent = `${done ? '✓' : enemy.icon} ${enemy.name}`; track.appendChild(node); }); this.byId('mcName').textContent = current.name; this.byId('mcSub').textContent = current.sub; this.byId('mcBio').textContent = current.bio; const notice = this.byId('mItemEarned'); notice.style.display = state.lastItemEarned ? 'block' : 'none'; notice.textContent = state.lastItemEarned ? `Item obtido: ${state.lastItemEarned}` : ''; }
  renderBook(entries, unlocks) { const grid = this.byId('bkGrid'); grid.replaceChildren(); this.byId('bkEntry').style.display = 'none'; Object.entries(entries).forEach(([id, entry]) => { const card = this.document.createElement('button'); card.className = `bk-card${unlocks[id] ? '' : ' locked'}`; card.textContent = `${entry.icon} ${entry.name} — ${entry.sub}`; grid.appendChild(card); }); }
  setSettingsValues(musicVolume, sfxVolume, muted) { this.byId('musicVolume').value = musicVolume; this.byId('sfxVolume').value = sfxVolume; this.byId('muteAudio').checked = muted; }
  readSettingsValues() { return { musicVolume: Number(this.byId('musicVolume').value), sfxVolume: Number(this.byId('sfxVolume').value), muted: this.byId('muteAudio').checked }; }
  renderEnd(finalData, state) { this.byId('eOrn').textContent = finalData.orn; this.byId('eTitle').textContent = finalData.title; this.byId('eBadge').textContent = finalData.badge; this.byId('eTxt').textContent = finalData.txt; this.byId('eSW').textContent = state.globalRoute.g; this.byId('eSC').textContent = state.globalRoute.b; this.byId('eSS').textContent = state.globalRoute.s; this.byId('eItemN').textContent = finalData.itemN; this.byId('eItemD').textContent = finalData.itemD; this.showScreen('sE'); }
}
